#!/bin/bash

cp "${OPENSHIFT_REPO_DIR}wp-config-sample.php" "${OPENSHIFT_REPO_DIR}wp-config.php"

if [ -d "${OPENSHIFT_REPO_DIR}assets" ]; then
  rm -rf "${OPENSHIFT_REPO_DIR}assets"
fi

ln -s "${OPENSHIFT_DATA_DIR}uploads/" "${OPENSHIFT_REPO_DIR}assets"

php "${OPENSHIFT_REPO_DIR}ativaplugin.php"